import Head from 'next/head'
import useCurrentWeather from '../hooks/use-current-weather'

export default function Home() {

  return (
    <>
      <Head>
        <title>Weather-X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1></h1>
      </main>
    </>
  )
}
